version: "3"

services:
  postgres:
    image: postgres:15.0-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=dev_admin
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: redis_dev
    image: redis:7-alpine
    ports:
      - 6379:6379

volumes:
  postgres:
